site_name: Concord - Contrastive Learning for Cross-domain Reconciliation and Discovery
theme:
  name: material
  logo: 'images/logo.png'
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      accent: lime

nav:
  - Getting started: index.md
  - The Concord Framework: framework.md
  - Tutorials: 
    - Single batch, RNA-seq:
      - PBMC3k dataset, single batch: notebooks/concord_pbmc3k.ipynb
    - Multiple batch, RNA-seq:
      - Intestine development by Huycke et al.: notebooks/concord_Huycke.ipynb
      - Mouse organogenesis (100k cell subset) by Cao et al.: notebooks/concord_mouse_organogenesis_100k.ipynb
  - Advanced usage: advanced.md
  - API: api.md
  - About: about.md

plugins:
  - social
  - search
  - mkdocs-jupyter:
      include_source: True
      include_requirejs: True

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Gartner-Lab/Concord

extra_javascript:
  - https://cdn.plot.ly/plotly-2.35.2.min.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2023 <a href="https://github.com/Gartner-Lab"  target="_blank" rel="noopener">Gartner Lab</a>